spring:
  rabbitmq:
    host: 192.168.77.134
    password: guest
    username: guest
    listener:
      type: simple
      simple:
        default-requeue-rejected: false
        acknowledge-mode: manual